name: dart_desk_cli
description: Command-line interface for deploying and managing self-hosted Dart Desk CMS instances.
version: 0.1.0
homepage: https://github.com/ThangVuNguyenViet/dart_desk_cli
repository: https://github.com/ThangVuNguyenViet/dart_desk_cli
topics:
  - cms
  - cli
  - deploy

environment:
  sdk: ^3.5.0

executables:
  dartdesk: dart_desk_cli

dependencies:
  args: ^2.5.0
  http: ^1.2.0
  archive: ^4.0.2
  yaml: ^3.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
