name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: dart:3.5

    steps:
      - uses: actions/checkout@v4

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        run: dart analyze --fatal-infos

      - name: dart test
        run: dart test
